export const items = [
  {
    id: "1",
    src: "/images/recipes/1.jpg",
    new: true,
    userImg: "/images/temp/expert.jpg",
    title: "canned tuna gourment",
    rate: 4,
    numberOfRaters: 465,
    name: "Yumna jawad",
    date: "JULY 9,2021",
  },
  {
    id: "2",
    src: "/images/recipes/2.jpg",
    userImg: "/images/temp/expert.jpg",
    title: "pumpkin quinoa porridge",
    rate: 3,
    numberOfRaters: 466,
    name: "Yumna jawad",
    date: "JULY 9,2021",
  },
  {
    id: "3",
    src: "/images/recipes/3.jpg",
    userImg: "/images/temp/expert.jpg",
    title: "berry chia pudding",
    rate: 5,
    numberOfRaters: 465,
    name: "Yumna jawad",
    date: "JULY 9,2021",
  },
  {
    id: "4",
    src: "/images/recipes/1.jpg",
    userImg: "/images/temp/expert.jpg",
    title: "grilled fish fillet",
    rate: 4,
    numberOfRaters: 465,
    name: "Yumna jawad",
    date: "JULY 9,2021",
  },
  {
    id: "5",
    src: "/images/recipes/4.jpg",
    userImg: "/images/temp/expert.jpg",
    title: "blueberry vanilla chia pudding",
    rate: 4,
    numberOfRaters: 465,
    name: "Yumna jawad",
    date: "JULY 9,2021",
  },
  {
    id: "6",
    src: "/images/recipes/2.jpg",
    userImg: "/images/temp/expert.jpg",
    title: "avocado salad",
    rate: 4,
    numberOfRaters: 465,
    name: "Yumna jawad",
    date: "JULY 9,2021",
  },
  {
    id: "7",
    src: "/images/recipes/3.jpg",
    userImg: "/images/temp/expert.jpg",
    title: "digital marketing made easy",
    rate: 4,
    numberOfRaters: 465,
    name: "Yumna jawad",
    date: "JULY 9,2021",
  },
  {
    id: "8",
    src: "/images/recipes/1.jpg",
    userImg: "/images/temp/expert.jpg",
    title: "canned tuna gourment",
    rate: 4,
    numberOfRaters: 465,
    name: "Yumna jawad",
    date: "JULY 9,2021",
  },
  {
    id: "9",
    src: "/images/recipes/2.jpg",
    userImg: "/images/temp/expert.jpg",
    title: "pumpkin quioa porridge",
    rate: 4,
    numberOfRaters: 465,
    name: "Yumna jawad",
    date: "JULY 9,2021",
  },
  {
    id: "10",
    src: "/images/recipes/3.jpg",
    userImg: "/images/temp/expert.jpg",
    title: "Baby Basics put your title  ",
    rate: 4,
    numberOfRaters: 465,
    name: "Yumna jawad",
    date: "JULY 9,2021",
  },
  {
    id: "11",
    src: "/images/recipes/1.jpg",
    userImg: "/images/temp/expert.jpg",
    title: "Baby Basics put your title  ",
    rate: 4,
    numberOfRaters: 465,
    name: "Yumna jawad",
    date: "JULY 9,2021",
  },
  {
    id: "12",
    src: "/images/recipes/2.jpg",
    userImg: "/images/temp/expert.jpg",
    title: "Baby Basics put your title  ",
    rate: 4,
    numberOfRaters: 465,
    name: "Yumna jawad",
    date: "JULY 9,2021",
  },
  {
    id: "13",
    src: "/images/recipes/3.jpg",
    userImg: "/images/temp/expert.jpg",
    title: "Baby Basics put your title  ",
    rate: 4,
    numberOfRaters: 465,
    name: "Yumna jawad",
    date: "JULY 9,2021",
  },
  {
    id: "14",
    src: "/images/recipes/1.jpg",
    userImg: "/images/temp/expert.jpg",
    title: "Baby Basics put your title ",
    rate: 4,
    numberOfRaters: 465,
    name: "Yumna jawad",
    date: "JULY 9,2021",
  },
  {
    id: "15",
    src: "/images/recipes/2.jpg",
    userImg: "/images/temp/expert.jpg",
    title: "Baby Basics put your title ",
    rate: 4,
    numberOfRaters: 465,
    name: "Yumna jawad",
    date: "JULY 9,2021",
  },
  {
    id: "16",
    src: "/images/recipes/3.jpg",
    userImg: "/images/temp/expert.jpg",
    title: "Baby Basics put your title ",
    rate: 4,
    numberOfRaters: 465,
    name: "Yumna jawad",
    date: "JULY 9,2021",
  },
  {
    id: "17",
    src: "/images/recipes/1.jpg",
    userImg: "/images/temp/expert.jpg",
    title: "Baby Basics put your title ",
    rate: 4,
    numberOfRaters: 465,
    name: "Yumna jawad",
    date: "JULY 9,2021",
  },
  {
    id: "18",
    src: "/images/recipes/2.jpg",
    userImg: "/images/temp/expert.jpg",
    title: "Baby Basics put your title ",
    rate: 4,
    numberOfRaters: 465,
    name: "Yumna jawad",
    date: "JULY 9,2021",
  },
  {
    id: "19",
    src: "/images/recipes/3.jpg",
    userImg: "/images/temp/expert.jpg",
    title: "Baby Basics put your title ",
    rate: 4,
    numberOfRaters: 465,
    name: "Yumna jawad",
    date: "JULY 9,2021",
  },
  {
    id: "20",
    src: "/images/recipes/1.jpg",
    userImg: "/images/temp/expert.jpg",
    title: "Baby Basics put your title ",
    rate: 4,
    numberOfRaters: 465,
    name: "Yumna jawad",
    date: "JULY 9,2021",
  },
];
